---
name: Python Coding Standards
on:
  pull_request:
    types:
      - opened
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Python coding standards check.
    steps:
      - name: Build and install Python dependencies.
        run: >
          $(command -v wget) --no-check-certificate
          https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh

          $(command -v sh) Miniconda3-py39_4.10.3-Linux-x86_64.sh -b -p miniconda

          $(command -v python) -m pip install --upgrade pip

          $(command -v pip) install pycodestyle
      - name: Checkout ufs_tcdiags.
        uses: actions/checkout@v2
        with:
          path: ufs_tcdiags
      - name: Run pycodestyle application.
        run: >
          cd "${GITHUB_WORKSPACE}/ufs_tcdiags

          $(command -v pycodestyle) -v --config "${GITHUB_WORKSPACE}"/ufs_tcdiags/.pycodestyle sorc/tcdiags

          $(command -v pycodestyle) -v --config "${GITHUB_WORKSPACE}"/ufs_tcdiags/.pycodestyle scripts

          $(command -v pycodestyle) -v --config "${GITHUB_WORKSPACE}"/ufs_tcdiags/.pycodestyle jupyter/ush
